### ISSUE TITLE
Shift animation being too low

### ISSUE THREAD

**Issue by BootSwitch** [Toshimichi0915/giz5#1]
Hey, maybe make it so it's more like the 1.8.9 or 1.7.10 animation with the sneaking, because when you shift, it goes too low. This mod is so good though.

**Comment by Toshimichi0915** [comment]
I released giz5 1.4.0 with soft shift animation
If you are satisfied with it please close the issue :)
https://github.com/Toshimichi0915/giz5/releases/tag/v1.4.0

**Comment by BootSwitch** [comment]
Works great, this mod is so good. Thank you!
