### ISSUE TITLE
Mod crashing with tweakeroo

### ISSUE THREAD

**Issue by KaxonDev** [Toshimichi0915/giz5#3]
`[21:25:08] [main/FATAL]: Mixin apply failed mixins.tweakeroo.json:MixinHeldItemRenderer -> net.minecraft.class_759: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_759::redirectedGetCooledAttackStrength with priority 1000 cannot inject into net/minecraft/class_759::method_3220()V merged by me.hp20.giz5.mixin.HeldItemRendererMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.tweakeroo.json:MixinHeldItemRenderer -> Prepare Injections ->  -> redirect$zjk000$redirectedGetCooledAttackStrength(Lnet/minecraft/class_746;F)F -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_759::redirectedGetCooledAttackStrength with priority 1000 cannot inject into net/minecraft/class_759::method_3220()V merged by me.hp20.giz5.mixin.HeldItemRendererMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.tweakeroo.json:MixinHeldItemRenderer -> Prepare Injections ->  -> redirect$zjk000$redirectedGetCooledAttackStrength(Lnet/minecraft/class_746;F)F -> Prepare]`

**Comment by Toshimichi0915** [comment]
Fixed!
You can now download [the newer version](https://github.com/Toshimichi0915/giz5/releases/tag/v1.5.3)
Thanks for reporting :)
