### ISSUE TITLE
question

### ISSUE THREAD

**Issue by itsbumble** [Toshimichi0915/giz5#5]
is ignorecooldown fully client side/visual or does it actually alter pvp in a cheat like way

**Comment by itsbumble** [comment]
also, a real issue i found was that the config resets every time i open my game

**Comment by itsbumble** [comment]
also, an issue i found is that editing the config in game then restarting the game resets the config. this doesnt occur when using the giz5.json file

**Comment by Toshimichi0915** [comment]
Hi, thanks for opening issue!
IgnoreCooldown is fully client-sided and just removes cooldown animation from your main hand!
I fixed the issue where the config was not saved properly. Please download the 1.5.4 from [here](https://github.com/Toshimichi0915/giz5/releases/tag/v1.5.4)
